management:
  endpoint:
    web:
      exposure:
        include: info, refresh, health
logging:
  level:
    org.springframework.cloud.kubernetes: DEBUG

spring:
  application:
    name: minikube-sample
